"""Full inventory of the four source guides.

via:
  profile              — written into profiles/*.mobileconfig; applies on a normal iPhone (no wipe)
  profile-supervised   — only in wipe-required/OpenHat-Supervised.mobileconfig; needs Supervised (full erase)
  manual               — user must tap in Settings; a profile cannot set this
  skipped              — deliberately not automated (destructive, anti-theft, or needs credentials)
  app                  — recommended app/service, not a system toggle
"""

from __future__ import annotations

# Public iOS this catalog is built against. Unknown restriction keys are
# ignored on older builds. iOS 27 beta is not supported.
CURRENT_PUBLIC_IOS = "26.6"
MIN_IOS_FULL_RESTRICTIONS = "18.2"
MIN_IOS_SAFARI_DENYLIST = "16"
MIN_IOS_ENCRYPTED_DNS = "14"

SOURCES = {
    "encrypted-dns": "paulmillr/encrypted-dns",
    "celenityy": "celenityy/ios-settings",
    "iprivacy": "iPrivacyGuides/iOS-Privacy-Guide",
    "builder": "danieloz147/ios-profile-builder",
    "apple": "Apple Restrictions payload",
}

# Each item: id, title, category, source, via, after, verify, notes
# Optional: key, value (restriction payload), apple_default, payload (dns/passcode/webclip)

CATALOG: list[dict] = [
    # --- Encrypted DNS (paulmillr) ---
    {
        "id": "dns-doh",
        "title": "Encrypted DNS over HTTPS (system-wide)",
        "category": "Network",
        "source": ["encrypted-dns", "celenityy", "iprivacy"],
        "via": "profile",
        "after": "Mullvad Adblock DoH (or Quad9 if you install that file)",
        "apple_default": "Carrier / router DNS, unencrypted",
        "verify": "Settings → General → VPN & Device Management → DNS / OpenHat Max Privacy",
        "notes": "Hides DNS from the carrier and blocks ads/trackers (Mullvad Adblock). iOS only uses one DNS profile.",
    },
    {
        "id": "dns-quad9",
        "title": "Optional DNS: Quad9 instead of Mullvad",
        "category": "Network",
        "source": ["encrypted-dns", "celenityy"],
        "via": "profile",
        "after": "Install OpenHat-MaxPrivacy-Quad9.mobileconfig to replace Mullvad",
        "apple_default": "n/a",
        "verify": "Same DNS screen; server should show dns.quad9.net",
        "notes": "Swiss malware-blocking resolver. Installing it replaces the Mullvad profile (same identifier).",
    },
    # --- Telemetry / ads (all guides + Apple keys) ---
    {
        "id": "analytics",
        "title": "Share iPhone Analytics",
        "category": "Apple telemetry",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "allowDiagnosticSubmission",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Privacy & Security → Analytics & Improvements → Share iPhone Analytics",
        "notes": "If the toggle is greyed out after install, the profile owns it.",
    },
    {
        "id": "analytics-lock",
        "title": "Lock analytics toggle so it cannot be turned back on",
        "category": "Apple telemetry",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowDiagnosticSubmissionModification",
        "value": False,
        "apple_default": "User can change it",
        "after": "Locked off (supervised only)",
        "verify": "Same Analytics screen; toggle should be disabled on a supervised device",
        "notes": "Ignored on a normal personal iPhone.",
    },
    {
        "id": "icloud-analytics",
        "title": "Share iCloud Analytics",
        "category": "Apple telemetry",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "On if signed into iCloud",
        "after": "Off",
        "verify": "Settings → Privacy & Security → Analytics & Improvements → Share iCloud Analytics",
        "notes": "No separate profile key; turn it off next to iPhone Analytics.",
    },
    {
        "id": "improve-siri",
        "title": "Improve Siri & Dictation",
        "category": "Apple telemetry",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Privacy & Security → Analytics & Improvements → Improve Siri & Dictation",
        "notes": "Profile also forces on-device dictation so audio is not sent to Siri servers.",
    },
    {
        "id": "personalized-ads",
        "title": "Apple personalized ads",
        "category": "Apple telemetry",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "allowApplePersonalizedAdvertising",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Privacy & Security → Apple Advertising → Personalized Ads",
        "notes": "",
    },
    {
        "id": "att",
        "title": "Allow Apps to Request to Track",
        "category": "Third-party tracking",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "forceLimitAdTracking",
        "value": True,
        "apple_default": "On (apps can prompt)",
        "after": "Off; Limit Ad Tracking forced",
        "verify": "Settings → Privacy & Security → Tracking",
        "notes": "forceLimitAdTracking also disables the tracking prompt.",
    },
    {
        "id": "ondevice-dictation",
        "title": "Dictation stays on-device",
        "category": "Apple telemetry",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "forceOnDeviceOnlyDictation",
        "value": True,
        "apple_default": "May use Siri servers",
        "after": "On-device only",
        "verify": "Keyboard dictation still works; no Siri server round-trip for dictation",
        "notes": "",
    },
    {
        "id": "ondevice-translate",
        "title": "Translation stays on-device",
        "category": "Apple telemetry",
        "source": ["celenityy", "apple"],
        "via": "profile",
        "key": "forceOnDeviceOnlyTranslation",
        "value": True,
        "apple_default": "May use Siri servers",
        "after": "On-device only",
        "verify": "Settings → Apps → Translate → On-Device Mode",
        "notes": "",
    },
    {
        "id": "ext-ai",
        "title": "External Apple Intelligence / ChatGPT-style integrations",
        "category": "Apple telemetry",
        "source": ["celenityy", "apple"],
        "via": "profile",
        "key": "allowExternalIntelligenceIntegrations",
        "value": False,
        "apple_default": "On (iOS 18.2+)",
        "after": "Off",
        "verify": "Apple Intelligence settings; external model providers unavailable",
        "notes": "Apple currently allows this on unsupervised devices; they say it will require supervision later.",
    },
    {
        "id": "ext-ai-signin",
        "title": "Sign-in to external intelligence providers",
        "category": "Apple telemetry",
        "source": ["apple"],
        "via": "profile",
        "key": "allowExternalIntelligenceIntegrationsSignIn",
        "value": False,
        "apple_default": "Allowed",
        "after": "Forced anonymous / signed out",
        "verify": "Same Apple Intelligence settings",
        "notes": "",
    },
    # --- iCloud / continuity ---
    {
        "id": "icloud-backup",
        "title": "iCloud Backup",
        "category": "iCloud",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "allowCloudBackup",
        "value": False,
        "apple_default": "On if iCloud is signed in",
        "after": "Off",
        "verify": "Settings → [your name] → iCloud → iCloud Backup",
        "notes": "Use encrypted Finder/iTunes backups instead. forceEncryptedBackup is also set.",
    },
    {
        "id": "encrypted-backup",
        "title": "Encrypt computer backups",
        "category": "iCloud",
        "source": ["iprivacy", "apple"],
        "via": "profile",
        "key": "forceEncryptedBackup",
        "value": True,
        "apple_default": "Optional",
        "after": "Required",
        "verify": "Finder or iTunes backup dialog requires a password",
        "notes": "",
    },
    {
        "id": "icloud-docs",
        "title": "iCloud Drive / document sync",
        "category": "iCloud",
        "source": ["celenityy", "apple"],
        "via": "profile",
        "key": "allowCloudDocumentSync",
        "value": False,
        "apple_default": "On",
        "after": "Off (may need supervision on iOS 13+)",
        "verify": "Settings → [your name] → iCloud → iCloud Drive",
        "notes": "Apple marked this supervised-only on newer iOS; still included. Confirm in Settings.",
    },
    {
        "id": "icloud-keychain",
        "title": "iCloud Keychain",
        "category": "iCloud",
        "source": ["celenityy", "apple"],
        "via": "profile",
        "key": "allowCloudKeychainSync",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → [your name] → iCloud → Passwords and Keychain",
        "notes": "Use Bitwarden or Proton Pass instead, as both guides recommend.",
    },
    {
        "id": "handoff",
        "title": "Handoff / Continuity (activity continuation)",
        "category": "iCloud",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "allowActivityContinuation",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → General → AirPlay & Handoff → Handoff",
        "notes": "",
    },
    {
        "id": "shared-stream",
        "title": "Shared Photo Stream / iCloud Shared Albums",
        "category": "iCloud",
        "source": ["celenityy", "apple"],
        "via": "profile",
        "key": "allowSharedStream",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Apps → Photos → Shared Albums",
        "notes": "",
    },
    {
        "id": "photo-stream",
        "title": "My Photo Stream",
        "category": "iCloud",
        "source": ["apple"],
        "via": "profile",
        "key": "allowPhotoStream",
        "value": False,
        "apple_default": "On (older iOS)",
        "after": "Off",
        "verify": "Photos settings (removed on iOS 17+)",
        "notes": "Deprecated on iOS 17+; harmless if ignored.",
    },
    {
        "id": "spotlight-web",
        "title": "Siri / Spotlight internet suggestions",
        "category": "Apple telemetry",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "allowSpotlightInternetResults",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Apple Intelligence & Siri → Suggestions from Apple / Content from Apple",
        "notes": "",
    },
    {
        "id": "auto-unlock",
        "title": "Auto Unlock with Watch / nearby Apple devices",
        "category": "Lock screen",
        "source": ["apple"],
        "via": "profile",
        "key": "allowAutoUnlock",
        "value": False,
        "apple_default": "On if Watch is paired",
        "after": "Off",
        "verify": "Watch / Face ID settings",
        "notes": "",
    },
    {
        "id": "managed-cloud-sync",
        "title": "Managed apps iCloud sync",
        "category": "iCloud",
        "source": ["apple"],
        "via": "profile",
        "key": "allowManagedAppsCloudSync",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Only relevant if MDM apps are present",
        "notes": "",
    },
    {
        "id": "enterprise-book-backup",
        "title": "Enterprise book backup / metadata sync",
        "category": "iCloud",
        "source": ["apple"],
        "via": "profile",
        "key": "allowEnterpriseBookBackup",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "n/a on a personal phone",
        "notes": "Paired with allowEnterpriseBookMetadataSync=false.",
    },
    {
        "id": "enterprise-book-meta",
        "title": "Enterprise book metadata sync",
        "category": "iCloud",
        "source": ["apple"],
        "via": "profile",
        "key": "allowEnterpriseBookMetadataSync",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "n/a on a personal phone",
        "notes": "",
    },
    {
        "id": "roaming-fetch",
        "title": "Background fetch while roaming",
        "category": "Network",
        "source": ["apple"],
        "via": "profile",
        "key": "allowGlobalBackgroundFetchWhenRoaming",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Cellular roaming behavior",
        "notes": "",
    },
    {
        "id": "remote-observe",
        "title": "Remote screen observation (Classroom)",
        "category": "Lock screen",
        "source": ["apple"],
        "via": "profile",
        "key": "allowRemoteScreenObservation",
        "value": False,
        "apple_default": "Allowed",
        "after": "Off",
        "verify": "Classroom app cannot observe the screen",
        "notes": "",
    },
    {
        "id": "airdrop-unmanaged",
        "title": "Treat AirDrop as unmanaged",
        "category": "Lock screen",
        "source": ["apple"],
        "via": "profile",
        "key": "forceAirDropUnmanaged",
        "value": True,
        "apple_default": "Managed if MDM",
        "after": "Unmanaged drop target",
        "verify": "n/a on a personal phone without MDM",
        "notes": "",
    },
    {
        "id": "airplay-password",
        "title": "Require pairing password for outgoing AirPlay",
        "category": "Network",
        "source": ["celenityy", "apple"],
        "via": "profile",
        "key": "forceAirPlayOutgoingRequestsPairingPassword",
        "value": True,
        "apple_default": "Not required",
        "after": "Required",
        "verify": "AirPlay to a TV prompts for a password",
        "notes": "",
    },
    {
        "id": "enterprise-trust",
        "title": "Trust Enterprise Developer button",
        "category": "Apps",
        "source": ["apple", "builder"],
        "via": "profile",
        "key": "allowEnterpriseAppTrust",
        "value": False,
        "apple_default": "On",
        "after": "Off — unsigned enterprise apps cannot be newly trusted",
        "verify": "Settings → General → VPN & Device Management (no Trust button)",
        "notes": "Does not revoke trust already granted. Blocks a common malware sideload path.",
    },
    # --- Safari ---
    {
        "id": "safari-fraud",
        "title": "Safari fraudulent website warning",
        "category": "Safari",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "safariForceFraudWarning",
        "value": True,
        "apple_default": "On, but user can disable",
        "after": "Forced on",
        "verify": "Settings → Apps → Safari → Fraudulent Website Warning",
        "notes": "",
    },
    {
        "id": "safari-cookies",
        "title": "Prevent Cross-Site Tracking (cookies)",
        "category": "Safari",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "safariAcceptCookies",
        "value": 1,
        "apple_default": "User can toggle",
        "after": "Prevent Cross-Site Tracking locked on",
        "verify": "Settings → Apps → Safari → Prevent Cross-Site Tracking",
        "notes": "Value 1 = tracking prevention on; user can still enable Block All Cookies.",
    },
    {
        "id": "safari-popups",
        "title": "Safari pop-up windows",
        "category": "Safari",
        "source": ["celenityy", "apple"],
        "via": "profile",
        "key": "safariAllowPopups",
        "value": False,
        "apple_default": "Blocked, user can enable",
        "after": "Blocked",
        "verify": "Settings → Apps → Safari → Block Pop-ups",
        "notes": "",
    },
    {
        "id": "untrusted-tls",
        "title": "Reject untrusted HTTPS certificates without prompting",
        "category": "Network",
        "source": ["apple"],
        "via": "profile",
        "key": "allowUntrustedTLSPrompt",
        "value": False,
        "apple_default": "User is prompted",
        "after": "Automatically rejected",
        "verify": "Visiting a site with a bad cert fails closed",
        "notes": "Stops a class of captive-portal and MITM prompts. Hotel Wi-Fi login pages may break until you use the captive-portal sheet.",
    },
    # --- Lock screen (profile) ---
    {
        "id": "ls-cc",
        "title": "Control Center on Lock Screen",
        "category": "Lock screen",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "allowLockScreenControlCenter",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Lock the phone and swipe for Control Center — it should not appear",
        "notes": "",
    },
    {
        "id": "ls-notifications",
        "title": "Notification Center history on Lock Screen",
        "category": "Lock screen",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "allowLockScreenNotificationsView",
        "value": False,
        "apple_default": "On",
        "after": "Off (new banners can still appear)",
        "verify": "Lock screen cannot open past notifications",
        "notes": "Also set Show Previews to When Unlocked manually.",
    },
    {
        "id": "ls-today",
        "title": "Today View / Search on Lock Screen",
        "category": "Lock screen",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "allowLockScreenTodayView",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Cannot swipe to Today View while locked",
        "notes": "",
    },
    {
        "id": "ls-wallet",
        "title": "Wallet / Passbook on Lock Screen",
        "category": "Lock screen",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "allowPassbookWhileLocked",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Face ID & Passcode → Wallet",
        "notes": "",
    },
    {
        "id": "siri-locked",
        "title": "Siri while locked",
        "category": "Lock screen",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile",
        "key": "allowAssistantWhileLocked",
        "value": False,
        "apple_default": "On",
        "after": "Off",
        "verify": "Side button Siri does nothing on the lock screen",
        "notes": "",
    },
    # --- Supervised extras already in file ---
    {
        "id": "siri-off",
        "title": "Siri entirely off",
        "category": "Siri",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile-supervised",
        "key": "allowAssistant",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Apple Intelligence & Siri missing or disabled",
        "notes": "On a normal iPhone, turn Siri off manually (see manual list).",
    },
    {
        "id": "siri-ugc",
        "title": "Siri web / user-generated content",
        "category": "Siri",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowAssistantUserGeneratedContent",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Siri cannot query web UGC",
        "notes": "",
    },
    {
        "id": "dictation-off",
        "title": "Dictation off",
        "category": "Siri",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowDictation",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Microphone key on keyboard has no dictation",
        "notes": "Unsupervised devices still get on-device-only dictation from the other key.",
    },
    {
        "id": "airdrop-off",
        "title": "AirDrop off",
        "category": "Network",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile-supervised",
        "key": "allowAirDrop",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Settings → General → AirDrop",
        "notes": "On a normal iPhone set Receiving Off manually. Use LocalSend for local sharing.",
    },
    {
        "id": "gamecenter",
        "title": "Game Center",
        "category": "Apple apps",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowGameCenter",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Game Center icon gone on a supervised device",
        "notes": "",
    },
    {
        "id": "gc-friends",
        "title": "Game Center friends / multiplayer / chat",
        "category": "Apple apps",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowAddingGameCenterFriends",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Game Center social features",
        "notes": "Also allowMultiplayerGaming=false.",
    },
    {
        "id": "gc-multiplayer",
        "title": "Game Center multiplayer",
        "category": "Apple apps",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowMultiplayerGaming",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Game Center multiplayer",
        "notes": "",
    },
    {
        "id": "news",
        "title": "Apple News",
        "category": "Apple apps",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowNews",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "News app",
        "notes": "On a normal iPhone, delete or ignore News and turn off its Siri Learn From This App.",
    },
    {
        "id": "podcasts",
        "title": "Apple Podcasts",
        "category": "Apple apps",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowPodcasts",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Podcasts app",
        "notes": "",
    },
    {
        "id": "music-service",
        "title": "Apple Music streaming service",
        "category": "Apple apps",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowMusicService",
        "value": False,
        "apple_default": "On",
        "after": "Classic Music mode (supervised only)",
        "verify": "Music app",
        "notes": "",
    },
    {
        "id": "radio",
        "title": "Apple Music Radio",
        "category": "Apple apps",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowRadioService",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Music Radio",
        "notes": "",
    },
    {
        "id": "bookstore",
        "title": "Apple Book Store",
        "category": "Apple apps",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowBookstore",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Books app store tab",
        "notes": "",
    },
    {
        "id": "find-friends",
        "title": "Find My Friends / Share My Location",
        "category": "Location",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile-supervised",
        "key": "allowFindMyFriends",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Settings → [your name] → Find My → Share My Location",
        "notes": "Also allowFindMyFriendsModification=false. Do this manually on a normal iPhone.",
    },
    {
        "id": "find-friends-mod",
        "title": "Changing Find My Friends",
        "category": "Location",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowFindMyFriendsModification",
        "value": False,
        "apple_default": "Allowed",
        "after": "Locked (supervised only)",
        "verify": "Find My settings",
        "notes": "",
    },
    {
        "id": "app-clips",
        "title": "App Clips",
        "category": "Apps",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowAppClips",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "NFC / Safari App Clips do not install",
        "notes": "",
    },
    {
        "id": "marketplace",
        "title": "Third-party app marketplaces",
        "category": "Apps",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowMarketplaceAppInstallation",
        "value": False,
        "apple_default": "Allowed in some regions",
        "after": "Off (supervised only)",
        "verify": "Cannot install marketplace apps",
        "notes": "EU sideloading. Also allowWebDistributionAppInstallation=false.",
    },
    {
        "id": "web-dist",
        "title": "Web distribution app installs",
        "category": "Apps",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowWebDistributionAppInstallation",
        "value": False,
        "apple_default": "Allowed in some regions",
        "after": "Off (supervised only)",
        "verify": "Cannot install apps from websites",
        "notes": "",
    },
    {
        "id": "auto-app-dl",
        "title": "Automatic app downloads from other devices",
        "category": "Apps",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowAutomaticAppDownloads",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Settings → Apps → App Store → Automatic Downloads → Apps",
        "notes": "Turn this off manually on a normal iPhone. App Updates stay on.",
    },
    {
        "id": "proximity-setup",
        "title": "Set up nearby new devices (and iOS→Android transfer)",
        "category": "Lock screen",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowProximitySetupToNewDevice",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "No prompt to set up a nearby new device",
        "notes": "",
    },
    {
        "id": "pw-share",
        "title": "AirDrop / Passwords app password sharing",
        "category": "Passwords",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowPasswordSharing",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Cannot AirDrop a password",
        "notes": "",
    },
    {
        "id": "pw-proximity",
        "title": "Request passwords from nearby devices",
        "category": "Passwords",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowPasswordProximityRequests",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Nearby password requests",
        "notes": "",
    },
    {
        "id": "pw-autofill",
        "title": "iCloud Keychain AutoFill",
        "category": "Passwords",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowPasswordAutoFill",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Settings → General → AutoFill & Passwords",
        "notes": "Turn AutoFill off manually and use Bitwarden. Third-party managers still work when this key is false.",
    },
    {
        "id": "safari-autofill",
        "title": "Safari AutoFill (contacts / cards / passwords)",
        "category": "Safari",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "profile-supervised",
        "key": "safariAllowAutoFill",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Settings → Apps → Safari → AutoFill",
        "notes": "Disable Use Contact Info and Credit Cards manually on a normal iPhone.",
    },
    {
        "id": "auth-before-autofill",
        "title": "Require Face ID / passcode before AutoFill",
        "category": "Passwords",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "forceAuthenticationBeforeAutoFill",
        "value": True,
        "apple_default": "User choice",
        "after": "Required (supervised only)",
        "verify": "AutoFill prompts for Face ID",
        "notes": "",
    },
    {
        "id": "mirroring",
        "title": "iPhone Mirroring to Mac",
        "category": "iCloud",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowiPhoneMirroring",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Mac iPhone Mirroring app",
        "notes": "",
    },
    {
        "id": "widgets-mac",
        "title": "iPhone widgets on Mac",
        "category": "iCloud",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowiPhoneWidgetsOnMac",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Mac desktop widgets",
        "notes": "",
    },
    {
        "id": "live-voicemail",
        "title": "Live Voicemail (processed in the cloud on some versions)",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowLiveVoicemail",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Phone → Live Voicemail",
        "notes": "",
    },
    {
        "id": "rcs",
        "title": "RCS messaging (not end-to-end encrypted like iMessage)",
        "category": "Apps",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowRCSMessaging",
        "value": False,
        "apple_default": "On (iOS 18+)",
        "after": "Off (supervised only)",
        "verify": "Settings → Apps → Messages → RCS",
        "notes": "Turn RCS off manually on a normal iPhone. Prefer Signal.",
    },
    {
        "id": "facetime-remote",
        "title": "FaceTime remote control of this device",
        "category": "Lock screen",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowVideoConferencingRemoteControl",
        "value": False,
        "apple_default": "Allowed",
        "after": "Off (supervised only)",
        "verify": "FaceTime remote control requests",
        "notes": "",
    },
    {
        "id": "airprint-ibeacon",
        "title": "AirPrint iBeacon discovery (phishing beacons)",
        "category": "Network",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowAirPrintiBeaconDiscovery",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "AirPrint printer discovery",
        "notes": "",
    },
    {
        "id": "airprint-tls",
        "title": "Require trusted TLS for AirPrint",
        "category": "Network",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "forceAirPrintTrustedTLSRequirement",
        "value": True,
        "apple_default": "Not required",
        "after": "Required (supervised only)",
        "verify": "AirPrint to untrusted printers fails",
        "notes": "",
    },
    {
        "id": "host-pairing",
        "title": "USB pairing with computers",
        "category": "Lock screen",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowHostPairing",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Finder/iTunes cannot pair",
        "notes": "Blocks a common forensic/extraction path. Also turn off USB Accessories on Lock Screen manually.",
    },
    {
        "id": "auto-datetime",
        "title": "Set Date & Time automatically (locked on)",
        "category": "Network",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "forceAutomaticDateAndTime",
        "value": True,
        "apple_default": "On, user can disable",
        "after": "Forced on (supervised only)",
        "verify": "Settings → General → Date & Time → Set Automatically",
        "notes": "Keep this on manually. Wrong clocks break TLS.",
    },
    {
        "id": "definition-lookup",
        "title": "Lookup / definition (sends highlighted text to Apple)",
        "category": "Siri",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowDefinitionLookup",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Look Up in selected text",
        "notes": "",
    },
    {
        "id": "genmoji",
        "title": "Genmoji / Image Playground / Image Wand / Writing Tools",
        "category": "Siri",
        "source": ["celenityy", "apple"],
        "via": "profile-supervised",
        "key": "allowGenmoji",
        "value": False,
        "apple_default": "On (Apple Intelligence)",
        "after": "Off (supervised only)",
        "verify": "Keyboard Genmoji / Image Playground",
        "notes": "Also allowImagePlayground, allowImageWand, allowWritingTools, allowPersonalizedHandwritingResults, allowAppleIntelligenceReport, Mail/Notes/Safari summaries.",
    },
    {
        "id": "image-playground",
        "title": "Image Playground",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowImagePlayground",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Image Playground app",
        "notes": "",
    },
    {
        "id": "image-wand",
        "title": "Image Wand",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowImageWand",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Notes Image Wand",
        "notes": "",
    },
    {
        "id": "writing-tools",
        "title": "Apple Intelligence writing tools",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowWritingTools",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Writing Tools menu",
        "notes": "",
    },
    {
        "id": "handwriting-ai",
        "title": "Personalized handwriting generation",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowPersonalizedHandwritingResults",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Apple Intelligence handwriting",
        "notes": "",
    },
    {
        "id": "ai-report",
        "title": "Apple Intelligence reports",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowAppleIntelligenceReport",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Apple Intelligence report",
        "notes": "",
    },
    {
        "id": "mail-smart",
        "title": "Mail smart replies / summaries",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowMailSmartReplies",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Mail compose",
        "notes": "Also allowMailSummary=false.",
    },
    {
        "id": "mail-summary",
        "title": "Mail summaries",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowMailSummary",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Mail summary UI",
        "notes": "",
    },
    {
        "id": "notes-transcribe",
        "title": "Notes transcription / summary",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowNotesTranscription",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Notes",
        "notes": "Also allowNotesTranscriptionSummary=false.",
    },
    {
        "id": "notes-summary",
        "title": "Notes transcription summary",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowNotesTranscriptionSummary",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Notes",
        "notes": "",
    },
    {
        "id": "safari-summary",
        "title": "Safari page summaries",
        "category": "Safari",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowSafariSummary",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Safari summarize button",
        "notes": "",
    },
    {
        "id": "visual-intel",
        "title": "Visual intelligence summaries",
        "category": "Siri",
        "source": ["apple"],
        "via": "profile-supervised",
        "key": "allowVisualIntelligenceSummary",
        "value": False,
        "apple_default": "On",
        "after": "Off (supervised only)",
        "verify": "Camera visual intelligence",
        "notes": "",
    },
    # --- MANUAL: remaining from both guides ---
    {
        "id": "location-master",
        "title": "Location Services master switch",
        "category": "Location",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Privacy & Security → Location Services",
        "notes": "Apple will not let a profile flip this. Required for emergency/Find My accuracy if you leave Find My on.",
    },
    {
        "id": "significant-locations",
        "title": "Significant Locations — clear and off",
        "category": "Location",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "On",
        "after": "History cleared, toggle off",
        "verify": "Location Services → System Services → Significant Locations",
        "notes": "",
    },
    {
        "id": "system-services-loc",
        "title": "Location System Services (analytics, routing, cell search, timezone, networking)",
        "category": "Location",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Mostly on",
        "after": "Off: iPhone Analytics, Routing & Traffic, Improve Maps, Setting Time Zone, Networking & Wireless, Cell Network Search, System Customization, Location-Based Alerts/Suggestions, Compass Calibration, Device Management, HomeKit, Motion Calibration (if unused)",
        "verify": "Location Services → System Services",
        "notes": "Leave Status Bar Icon on so you can see when something still uses GPS.",
    },
    {
        "id": "lockdown",
        "title": "Lockdown Mode",
        "category": "Lock screen",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "Off",
        "after": "On; 2G cellular off",
        "verify": "Settings → Privacy & Security → Lockdown Mode",
        "notes": "Requires passcode. A profile cannot enable this.",
    },
    {
        "id": "apple-id",
        "title": "Sign out of iCloud / Apple ID, or strip every iCloud toggle",
        "category": "iCloud",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Signed in, most sync on",
        "after": "Signed out, or Photos/Drive/Keychain/Messages/Health/Calendar/Contacts/Safari/Home/Wallet/Siri/Maps/Shortcuts/Backup all off",
        "verify": "Settings → [your name]",
        "notes": "If you keep iCloud: Advanced Data Protection on, Access iCloud Data on the Web off, 2FA / security keys on, communication emails off, Personalized Recommendations off.",
    },
    {
        "id": "icloud-photos",
        "title": "iCloud Photos",
        "category": "iCloud",
        "source": ["celenityy", "iprivacy"],
        "via": "skipped",
        "apple_default": "On if iCloud Photos is enabled",
        "after": "Off — do this yourself after photos are downloaded",
        "verify": "Settings → [your name] → iCloud → Photos",
        "notes": "A profile key exists (allowCloudPhotoLibrary=false) but Apple deletes local copies that were not fully downloaded. Too dangerous to automate.",
    },
    {
        "id": "find-my-device",
        "title": "Find My iPhone",
        "category": "Location",
        "source": ["celenityy"],
        "via": "skipped",
        "apple_default": "On",
        "after": "Left on (theft recovery). Turn off only if your threat model prefers that.",
        "verify": "Settings → [your name] → Find My",
        "notes": "celenityy recommends off. We do not force it: a stolen unsupervised phone with Find My off is gone.",
    },
    {
        "id": "private-wifi",
        "title": "Private Wi-Fi Address + Limit IP Address Tracking",
        "category": "Network",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Usually on for new networks",
        "after": "On for every network you use",
        "verify": "Settings → Wi-Fi → (i) next to the network",
        "notes": "Must be set per network. A Wi-Fi payload could do this only if we knew your SSID and password.",
    },
    {
        "id": "ask-join",
        "title": "Ask to Join Networks off; Auto-Join Hotspot Never",
        "category": "Network",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Ask / Automatic",
        "after": "Off / Never",
        "verify": "Settings → Wi-Fi",
        "notes": "",
    },
    {
        "id": "wifi-off-unused",
        "title": "Wi-Fi and Bluetooth off when unused; Airplane Mode when idle",
        "category": "Network",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off when you are not using them",
        "verify": "Control Center / Settings",
        "notes": "A profile cannot schedule radios.",
    },
    {
        "id": "siri-manual",
        "title": "Siri Listen for / Press Side Button off; all Apple suggestions off",
        "category": "Siri",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Apple Intelligence & Siri",
        "notes": "Required on a normal iPhone because allowAssistant is supervised-only.",
    },
    {
        "id": "airdrop-manual",
        "title": "AirDrop Receiving Off; no cellular for AirDrop",
        "category": "Network",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Contacts Only",
        "after": "Receiving Off",
        "verify": "Settings → General → AirDrop",
        "notes": "",
    },
    {
        "id": "handoff-manual",
        "title": "Continuity Camera off; Automatically AirPlay → Never; AirPlay Receiver off",
        "category": "iCloud",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "On / Automatic",
        "after": "Off / Never",
        "verify": "Settings → General → AirPlay & Handoff",
        "notes": "Handoff itself is also forced off by the profile.",
    },
    {
        "id": "lock-screen-rest",
        "title": "Lock Screen: USB Accessories, Live Activities, Home Control, Return Missed Calls off",
        "category": "Lock screen",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Mostly on",
        "after": "All Allow Access When Locked off",
        "verify": "Settings → Face ID & Passcode → Allow Access When Locked",
        "notes": "Control Center, Notification Center, Today View, and Wallet are already forced off by the profile.",
    },
    {
        "id": "passcode-strong",
        "title": "Long alphanumeric passcode; optional Face ID off; Erase Data on; Require Immediately",
        "category": "Lock screen",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "6-digit + Face ID",
        "after": "Custom alphanumeric; Face ID off if your threat model needs it; Erase Data on",
        "verify": "Settings → Face ID & Passcode",
        "notes": "Optional extra file OpenHat-Passcode.mobileconfig enforces min length 6, no simple PINs, lock immediately. It will refuse to install until the passcode complies.",
    },
    {
        "id": "notification-previews",
        "title": "Notification previews: When Unlocked; Screen Sharing notifications off",
        "category": "Lock screen",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Always",
        "after": "When Unlocked",
        "verify": "Settings → Notifications → Show Previews",
        "notes": "",
    },
    {
        "id": "focus-share",
        "title": "Focus: do not share across devices or share Focus Status",
        "category": "iCloud",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Focus",
        "notes": "",
    },
    {
        "id": "device-name",
        "title": "Device name: generic (not your real name)",
        "category": "Apps",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Adam's iPhone",
        "after": "Device or similar",
        "verify": "Settings → General → About → Name",
        "notes": "Visible on some networks.",
    },
    {
        "id": "software-update",
        "title": "Automatic iOS updates + Rapid Security Responses on",
        "category": "Apps",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Usually on",
        "after": "On",
        "verify": "Settings → General → Software Update → Automatic Updates",
        "notes": "Delay major version jumps a few weeks; install 15.x.y / 16.x.y patches immediately.",
    },
    {
        "id": "bg-refresh",
        "title": "Background App Refresh: off except messaging",
        "category": "Apps",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "On for most apps",
        "after": "Off except Signal / mail",
        "verify": "Settings → General → Background App Refresh",
        "notes": "",
    },
    {
        "id": "app-store",
        "title": "App Store: auto app downloads off, updates on, video autoplay off, in-app ratings off",
        "category": "Apps",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Mixed",
        "after": "Updates on; everything else off",
        "verify": "Settings → Apps → App Store",
        "notes": "",
    },
    {
        "id": "safari-manual",
        "title": "Safari: DuckDuckGo, suggestions off, ad measurement off, camera/mic/location Deny, Hide IP from Trackers, Advanced Tracking on All Browsing",
        "category": "Safari",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Google, suggestions on",
        "after": "DuckDuckGo; all listed protections on",
        "verify": "Settings → Apps → Safari",
        "notes": "Also set Downloads to On My iPhone, Close Tabs After One Day, Block Pop-ups (profile helps), no AutoFill.",
    },
    {
        "id": "permissions",
        "title": "Audit Camera, Mic, Contacts, Photos (never All Photos), Bluetooth, Local Network, Speech, Motion",
        "category": "Third-party tracking",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Whatever you granted",
        "after": "Least privilege; Speech Recognition never",
        "verify": "Settings → Privacy & Security (each permission page)",
        "notes": "A profile cannot revoke existing third-party grants.",
    },
    {
        "id": "privacy-report",
        "title": "App Privacy Report on",
        "category": "Third-party tracking",
        "source": ["iprivacy"],
        "via": "manual",
        "apple_default": "Off",
        "after": "On",
        "verify": "Settings → Privacy & Security → App Privacy Report",
        "notes": "This is the closest built-in view of which servers apps contact. It is not a settings dump.",
    },
    {
        "id": "siri-per-app",
        "title": "Per-app: Learn from this App / Suggest App / Show on Home Screen off",
        "category": "Siri",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off for every app, especially App Store, Safari, Maps, Photos, Health, TV",
        "verify": "Settings → Apps → [app] → Siri & Search",
        "notes": "",
    },
    {
        "id": "imessage-email",
        "title": "iMessage / FaceTime reachable only at your phone number, not email; RCS off",
        "category": "Apps",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "Email + phone; RCS on",
        "after": "Phone number only; RCS off",
        "verify": "Settings → Apps → Messages → Send & Receive; FaceTime; RCS",
        "notes": "We do not disable iMessage in the profile (allowChat would brick Messages on supervised phones).",
    },
    {
        "id": "contacts-photo",
        "title": "Share Name and Photo off; Calendar location suggestions off; Reminders suggestions off",
        "category": "Apps",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Apps → Contacts / Calendar / Reminders",
        "notes": "",
    },
    {
        "id": "maps-contribute",
        "title": "Maps: Ratings and Photos off; photo providers off",
        "category": "Apps",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Apps → Maps → Contribute to Maps",
        "notes": "",
    },
    {
        "id": "photos-manual",
        "title": "Photos: Shared Albums off, cellular off, featured content off, Use Passcode on Hidden album",
        "category": "Apps",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "Mixed",
        "after": "As listed",
        "verify": "Settings → Apps → Photos",
        "notes": "",
    },
    {
        "id": "tv-history",
        "title": "TV: Use Play History off; autoplay next off",
        "category": "Apps",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Apps → TV",
        "notes": "",
    },
    {
        "id": "shortcuts-lock",
        "title": "Shortcuts: iCloud Sync off, Private Sharing off, Allow Running Scripts off",
        "category": "Apps",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "Sync on",
        "after": "Off",
        "verify": "Settings → Apps → Shortcuts",
        "notes": "",
    },
    {
        "id": "translate-cellular",
        "title": "Translate: cellular off, On-Device Mode on",
        "category": "Apps",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "Cellular on",
        "after": "On-device, Wi-Fi only",
        "verify": "Settings → Apps → Translate",
        "notes": "Profile already forces on-device translation.",
    },
    {
        "id": "passwords-compromised",
        "title": "Detect Compromised Passwords on; Delete After Use on",
        "category": "Passwords",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "Detect on",
        "after": "On",
        "verify": "Settings → Apps → Passwords",
        "notes": "Detect Compromised Passwords is local. Prefer Bitwarden as default manager.",
    },
    {
        "id": "screen-time",
        "title": "Screen Time Content & Privacy Restrictions (optional second lock)",
        "category": "Apps",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "Off",
        "after": "On: don't allow tracking requests, Apple Advertising, Share My Location, Speech Recognition, Bluetooth Sharing; Siri web search don't allow",
        "verify": "Settings → Screen Time → Content & Privacy Restrictions",
        "notes": "Overlaps the profile. Useful on a normal iPhone where supervised keys are ignored.",
    },
    {
        "id": "fitness",
        "title": "Fitness Tracking off if unused",
        "category": "Location",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off",
        "verify": "Settings → Privacy & Security → Motion & Fitness",
        "notes": "",
    },
    {
        "id": "wallet-cards",
        "title": "Wallet compatible cards / unused Apple Pay merchant ID off",
        "category": "Apps",
        "source": ["celenityy", "iprivacy"],
        "via": "manual",
        "apple_default": "On",
        "after": "Off if you do not use Apple Pay",
        "verify": "Settings → Wallet & Apple Pay; Location System Services → Apple Pay Merchant Identification",
        "notes": "",
    },
    {
        "id": "imessage-key-verify",
        "title": "iMessage Contact Key Verification on (if you keep iMessage)",
        "category": "Apps",
        "source": ["celenityy"],
        "via": "manual",
        "apple_default": "Off",
        "after": "On",
        "verify": "Settings → [your name] → Contact Key Verification",
        "notes": "",
    },
    {
        "id": "vpn",
        "title": "No-logs VPN: Mullvad, IVPN, or Proton VPN, always-on",
        "category": "Network",
        "source": ["celenityy", "iprivacy", "builder"],
        "via": "manual",
        "apple_default": "None",
        "after": "Installed, connected, kill switch on",
        "verify": "Settings → General → VPN & Device Management → VPN",
        "notes": "ios-profile-builder can emit a VPN payload, but only if you already have a server and credentials. We will not bake a third-party account into this file.",
    },
    {
        "id": "adguard",
        "title": "Optional: AdGuard Pro or Lockdown Privacy as a local DNS firewall + Safari content blockers",
        "category": "Network",
        "source": ["iprivacy", "celenityy"],
        "via": "app",
        "apple_default": "None",
        "after": "Installed if you want per-app query logs on top of system DoH",
        "verify": "App VPN/DNS permission; Safari → Extensions",
        "notes": "System encrypted DNS (this profile) already blocks trackers without consuming the VPN slot. AdGuard Pro uses a local VPN and will conflict with a real VPN unless you pick one.",
    },
    {
        "id": "browser",
        "title": "Firefox Focus or Brave as default browser; Safari only for persistent logins",
        "category": "Safari",
        "source": ["iprivacy", "celenityy"],
        "via": "app",
        "apple_default": "Safari",
        "after": "Focus/Brave default; telemetry off inside the app",
        "verify": "Settings → Apps → Safari → Default Browser App",
        "notes": "",
    },
    {
        "id": "bitwarden",
        "title": "Bitwarden or Proton Pass instead of iCloud Keychain",
        "category": "Passwords",
        "source": ["iprivacy", "celenityy"],
        "via": "app",
        "apple_default": "iCloud Keychain",
        "after": "Installed, AutoFill provider set",
        "verify": "Settings → General → AutoFill & Passwords",
        "notes": "",
    },
    {
        "id": "proton-mail",
        "title": "Proton Mail (or Tuta) instead of Gmail/Outlook apps",
        "category": "Apps",
        "source": ["iprivacy"],
        "via": "app",
        "apple_default": "Mail / Gmail",
        "after": "Proton app for encrypted mail; built-in Mail for conventional accounts",
        "verify": "Installed apps",
        "notes": "Do not install Gmail/Outlook/Yahoo apps.",
    },
    {
        "id": "signal",
        "title": "Signal for messaging; Standard Notes for notes; MySudo for burner numbers",
        "category": "Apps",
        "source": ["iprivacy"],
        "via": "app",
        "apple_default": "iMessage / Notes",
        "after": "Installed as needed",
        "verify": "Installed apps",
        "notes": "",
    },
    {
        "id": "localsend",
        "title": "LocalSend for local file/clipboard share (no Apple ID)",
        "category": "Network",
        "source": ["builder"],
        "via": "app",
        "apple_default": "AirDrop / Universal Clipboard",
        "after": "Installed on phone and Mac",
        "verify": "LocalSend on the same Wi-Fi",
        "notes": "AirDrop has no public plugin API. Universal Clipboard requires the same iCloud account.",
    },
    # --- SKIPPED builder payloads ---
    {
        "id": "skip-mdm",
        "title": "MDM enrollment payload",
        "category": "Skipped",
        "source": ["builder"],
        "via": "skipped",
        "apple_default": "None",
        "after": "Not included",
        "verify": "n/a",
        "notes": "ios-profile-builder can emit com.apple.mdm. That gives a remote server control of the phone — the opposite of this project.",
    },
    {
        "id": "skip-ca",
        "title": "Custom Root CA",
        "category": "Skipped",
        "source": ["builder"],
        "via": "skipped",
        "apple_default": "None",
        "after": "Not included",
        "verify": "n/a",
        "notes": "A custom CA enables HTTPS interception. We will not ship one.",
    },
    {
        "id": "skip-wifi-payload",
        "title": "Wi-Fi payload with your home SSID",
        "category": "Skipped",
        "source": ["builder"],
        "via": "skipped",
        "apple_default": "User joins networks",
        "after": "Not included",
        "verify": "n/a",
        "notes": "Needs your SSID and password. Set Private Address per network instead.",
    },
    {
        "id": "skip-imessage",
        "title": "Force-disable iMessage (allowChat)",
        "category": "Skipped",
        "source": ["celenityy", "apple"],
        "via": "skipped",
        "apple_default": "On",
        "after": "Left available; tighten Send & Receive manually",
        "verify": "Settings → Apps → Messages",
        "notes": "celenityy says turn iMessage off if unused. allowChat is supervised and would remove iMessage entirely, which is too sharp for a default profile.",
    },
    {
        "id": "skip-faceid",
        "title": "Force-disable Face ID / Touch ID",
        "category": "Skipped",
        "source": ["celenityy", "iprivacy", "apple"],
        "via": "skipped",
        "apple_default": "On",
        "after": "Your choice in Face ID & Passcode",
        "verify": "Settings → Face ID & Passcode",
        "notes": "allowFingerprintForUnlock=false is too easy to lock people out of a daily driver. Do it manually if your threat model needs it.",
    },
    {
        "id": "skip-private-relay",
        "title": "iCloud Private Relay / Mail Privacy Protection",
        "category": "Skipped",
        "source": ["apple"],
        "via": "skipped",
        "apple_default": "On with iCloud+",
        "after": "Left on — these are privacy features",
        "verify": "Settings → [your name] → iCloud → Private Relay; Mail Privacy Protection",
        "notes": "A profile can disable them. We do not.",
    },
    {
        "id": "skip-qos",
        "title": "Dark Mode, Night Shift, True Tone, Reduce Motion, battery percentage",
        "category": "Skipped",
        "source": ["celenityy"],
        "via": "skipped",
        "apple_default": "User preference",
        "after": "Unchanged",
        "verify": "Display & Brightness / Accessibility / Battery",
        "notes": "In celenityy's guide as comfort/battery, not telemetry. A profile cannot set most of these anyway.",
    },
    {
        "id": "watch-wrist",
        "title": "Force Apple Watch wrist detection",
        "category": "Lock screen",
        "source": ["apple"],
        "via": "profile",
        "key": "forceWatchWristDetection",
        "value": True,
        "apple_default": "User choice",
        "after": "On if a Watch is paired",
        "verify": "Watch unlocks only while on wrist",
        "notes": "Stops a removed Watch from unlocking the iPhone.",
    },
    {
        "id": "safari-denylist",
        "title": "Safari deny list for tracker / social-graph sites",
        "category": "Safari",
        "source": ["apple"],
        "via": "manual",
        "apple_default": "None",
        "after": "Install OpenHat-SafariDenyList.mobileconfig (iOS 16+)",
        "verify": "Safari cannot open facebook.com / instagram.com / doubleclick.net etc.",
        "notes": "Safari only. Native Instagram/Snapchat apps ignore this. Separate file so a filter rejection cannot break the main profile.",
    },
    {
        "id": "configurator-supervise",
        "title": "Supervise the iPhone with Apple Configurator",
        "category": "Apps",
        "source": ["apple"],
        "via": "manual",
        "apple_default": "Unsupervised",
        "after": "Supervised; then install wipe-required/OpenHat-Supervised.mobileconfig",
        "verify": "Settings → General → About → Supervised (or the profile applies AirDrop/Siri/app blocks)",
        "notes": "USB + a Mac. ERASES the entire iPhone. Isolated in wipe-required/ so it cannot be mixed with the no-wipe Safari profiles. See wipe-required/CONFIGURATOR.md.",
    },
    {
        "id": "tracker-apps-delete",
        "title": "Delete high-tracking apps (Instagram, Facebook, Messenger, Snapchat, TikTok, X, Pinterest, Reddit, LinkedIn)",
        "category": "Third-party tracking",
        "source": ["iprivacy", "celenityy"],
        "via": "manual",
        "apple_default": "Whatever you installed",
        "after": "Deleted, or Screen Time → Never Allow, or Supervised profile after Configurator",
        "verify": "Home Screen / App Library; data/tracker-apps.json has bundle IDs",
        "notes": "A Safari-installed profile cannot hide these apps. That is Apple, not a missing payload.",
    },
]


def restriction_keys(vias: tuple[str, ...]) -> dict:
    out = {}
    for item in CATALOG:
        if item.get("via") in vias and "key" in item:
            out[item["key"]] = item["value"]
    return out


def public_catalog() -> list[dict]:
    """JSON-safe copy for the installer page."""
    keep = (
        "id",
        "title",
        "category",
        "source",
        "via",
        "after",
        "apple_default",
        "verify",
        "notes",
        "key",
    )
    rows = []
    for item in CATALOG:
        row = {k: item[k] for k in keep if k in item}
        row["source"] = [SOURCES.get(s, s) for s in item["source"]]
        rows.append(row)
    return rows
